language: cpp

compiler:
 - clang
 - gcc

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:mapnik/boost
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev

script:
 - ./configure CXX=${CXX} CC=${CC} DEMO=False BINDINGS='python' CPP_TESTS=True CAIRO=False FAST=True && JOBS=2 make
 - make test-local

branches:
  only:
    - master
    - 2.3.x

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
